In [38]:
import csv, json
import pandas as pd
df=pd.read_csv("pincode.csv")

In [45]:
rows=df.loc[df['pincode'] == 282005]
type(rows)
rows

,pincode,divisionname,regionname,circlename,Taluk,Districtname,statename
125464,282005,Agra,Agra,Uttar Pradesh,NaN,Agra,UTTAR PRADESH
125513,282005,Agra,Agra,Uttar Pradesh,NaN,Agra,UTTAR PRADESH
125528,282005,Agra,Agra,Uttar Pradesh,NaN,Agra,UTTAR PRADESH
125542,282005,Agra,Agra,Uttar Pradesh,Agra,Agra,UTTAR PRADESH
125568,282005,Agra,Agra,Uttar Pradesh,NaN,Agra,UTTAR PRADESH
125611,282005,Agra,Agra,Uttar Pradesh,NaN,Agra,UTTAR PRADESH

In [31]:
df

,divisionname,regionname,circlename,Taluk,Districtname,statename
pincode,,,,,,
504273,Adilabad,Hyderabad,Andhra Pradesh,Asifabad,Adilabad,TELANGANA
504293,Adilabad,Hyderabad,Andhra Pradesh,Asifabad,Adilabad,TELANGANA
504307,Adilabad,Hyderabad,Andhra Pradesh,Boath,Adilabad,TELANGANA
504001,Adilabad,Hyderabad,Andhra Pradesh,Adilabad,Adilabad,TELANGANA
504001,Adilabad,Hyderabad,Andhra Pradesh,Adilabad,Adilabad,TELANGANA
...,...,...,...,...,...,...
721649,Tamluk,South Bengal,West Bengal,Nandakumar,East Midnapore,WEST BENGAL
721151,Tamluk,South Bengal,West Bengal,Panskura-i,East Midnapore,WEST BENGAL
721626,Tamluk,South Bengal,West Bengal,Bhagawanpur,East Midnapore,WEST BENGAL
721139,Tamluk,South Bengal,West Bengal,Panskura-i,East Midnapore,WEST BENGAL
721648,Tamluk,South Bengal,West Bengal,Nandakumar,East Midnapore,WEST BENGAL

In [8]:
GET https://api.postalpincode.in/pincode/110001

SyntaxError: invalid syntax (<ipython-input-8-8da5f4b14f08>, line 1)

In [50]:

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geoapiExercises")
zipcode1 = "282007"
print("\nZipcode:",zipcode1)
location = geolocator.geocode(zipcode1)
print(location)

Zipcode: 282007
{'place_id': 216581712, 'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'way', 'osm_id': 657262606, 'boundingbox': ['27.2063493', '27.2068025', '77.9718196', '77.9722795'], 'lat': '27.206575899999997', 'lon': '77.97204955000001', 'display_name': 'Bodla, à¤†à¤—à¤°à¤¾ - Agra, Agra, Uttar Pradesh, 282007, India', 'class': 'place', 'type': 'postcode', 'importance': 0.33499999999999996}

In [ ]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from urllib.request import urlopen 
import requests
import csv
import time
import io
import json

In [49]:


headers_std = {
'User-Agent': 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Safari/537.36',
}
import requests
resp = requests.get("https://pincode.saratchandra.in/api/pincode/282005")

print(resp.json())

{'status': 200, 'data': [{'pincode': '282005', 'office_name': 'Dayal Bagh S.O', 'delivery_status': 'Delivery', 'division_name': 'Agra', 'region_name': 'Agra', 'circle_name': 'Uttar Pradesh', 'district': 'Agra', 'state_name': 'UTTAR PRADESH', 'taluk': 'NA'}, {'pincode': '282005', 'office_name': 'Jaganpur B.O', 'delivery_status': 'Delivery', 'division_name': 'Agra', 'region_name': 'Agra', 'circle_name': 'Uttar Pradesh', 'district': 'Agra', 'state_name': 'UTTAR PRADESH', 'taluk': 'NA'}, {'pincode': '282005', 'office_name': 'K.H.Sansthan S.O', 'delivery_status': 'Non-Delivery', 'division_name': 'Agra', 'region_name': 'Agra', 'circle_name': 'Uttar Pradesh', 'district': 'Agra', 'state_name': 'UTTAR PRADESH', 'taluk': 'NA'}, {'pincode': '282005', 'office_name': 'Karmyogi Enclave S.O', 'delivery_status': 'Non-Delivery', 'division_name': 'Agra', 'region_name': 'Agra', 'circle_name': 'Uttar Pradesh', 'district': 'Agra', 'state_name': 'UTTAR PRADESH', 'taluk': 'Agra'}, {'pincode': '282005', 'office_name': 'Lawyers Colony S.O', 'delivery_status': 'Non-Delivery', 'division_name': 'Agra', 'region_name': 'Agra', 'circle_name': 'Uttar Pradesh', 'district': 'Agra', 'state_name': 'UTTAR PRADESH', 'taluk': 'NA'}, {'pincode': '282005', 'office_name': 'New Agra S.O', 'delivery_status': 'Non-Delivery', 'division_name': 'Agra', 'region_name': 'Agra', 'circle_name': 'Uttar Pradesh', 'district': 'Agra', 'state_name': 'UTTAR PRADESH', 'taluk': 'NA'}]}

In [ ]:
data={}

with open("pincode.csv") as csvFile:
    csvReader=csv.DictReader(csvFile)
    for rows in csvReader:
        id=rows['pincode']
        data[id]=rows
print(data)